# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: 'bundler'
    # Look for `Gemfile` in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
    labels:
      - "bundler"
      - "dependencies"


  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    labels:
      - "github_actions"
      - "dependencies"

  - package-ecosystem: "npm"
    # Look for `package.json` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    labels:
      - "node.js"
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/release"
    schedule:
      interval: "weekly"
    labels:
      - "pip"
      - "dependencies"
