name: Publish Docs to Github Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:

jobs:

  build:

    runs-on: self-hosted-small
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      run: |
        RUBY_BIN=$(readlink -f /usr/bin/ruby)
        mkdir -p ~/bin
        ln -sf /usr/bin/bundle${RUBY_BIN##*ruby} ~/bin/bundle

    - name: Install Ruby dependencies
      run: |
        export PATH=~/bin:$PATH
        bundle

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Antora and the Antora Lunr Extension
      run: npm i

    - name: Generate Site
      env:
        GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
      run: |
        export PATH=~/bin:$PATH
        make docs

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: build/site

  deploy:

    needs: build
    environment:
      name: github-pages
      url: https://cray-hpe.github.io/fawkes
    permissions:
      pages: write
      id-token: write
    runs-on: self-hosted-small
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
